### ISSUE TITLE
After upgrade opencms 10.5.1 to 10.5.2

### ISSUE THREAD

**Issue by leandrorp** [alkacon/opencms-core#516]
Hi,
After i run the wizard to upgrade the opencms 10.5.1 to 10.5.2.
This error is occurring :

[g.opencms.main.OpenCmsListener:  93] A Java system error occurred.
java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
	at org.opencms.monitor.CmsMemoryMonitor.createLRUCacheMap(CmsMemoryMonitor.java:316)
	at org.opencms.xml.CmsXmlEntityResolver.initCaches(CmsXmlEntityResolver.java:209)
	at org.opencms.xml.CmsXmlEntityResolver.cacheSystemId(CmsXmlEntityResolver.java:140)
	at org.opencms.configuration.CmsConfigurationManager.cacheDtdSystemId(CmsConfigurationManager.jav

Thanks

**Comment by leandrorp** [comment]
Hi
I found the problem, the guava-18.0.jar inside the opencms-upgrade-to-10.5.2.zip it was 1kb.
Thanks

**Comment by tHerrmann** [comment]
You were too quick. We replaced the broken updater this morning.
